#
# docker build --platform=linux/amd64 -f Dockerfile-syslinux -t pfdii-syslinux-installer .
#

FROM archlinux:latest

RUN pacman -Syu --noconfirm && \
    pacman -S --noconfirm dosfstools syslinux util-linux multipath-tools

#RUN pacman -S --noconfirm --needed efitools efibootmgr

##
## Optionally build the preloader-signed
##
#RUN curl -O https://aur.archlinux.org/cgit/aur.git/snapshot/preloader-signed.tar.gz && \
#     tar zxvf preloader-signed.tar.gz  && cd preloader-signed && useradd somebody && chown -R somebody:somebody .
#RUN pacman -Syu --noconfirm && \
#     pacman -S --noconfirm fakeroot
#USER somebody
#RUN cd preloader-signed && makepkg --syncdeps
#USER root
##
## Instead of building preloader-signed, just fetching the needed parts
#
RUN mkdir -p /preloader-signed && cd preloader-signed && \
    curl -O https://blog.hansenpartnership.com/wp-uploads/2013/HashTool.efi && \
    curl -O https://blog.hansenpartnership.com/wp-uploads/2013/PreLoader.efi
##

WORKDIR /workspace
VOLUME /workspace

COPY setup-syslinux.sh /bin/setup-syslinux.sh

ENTRYPOINT ["/bin/setup-syslinux.sh"]
CMD ["disk.img"]


#RUN pacman -Scc --noconfirm   # Clean the package cache to reduce the image size
