FROM ubuntu:22.04

RUN apt update && \
    apt install -y gcc-multilib g++-multilib make \
    		   gnome-common yelp-tools uuid-dev libparted-dev libglib2.0-dev libgtkmm-3.0-dev

WORKDIR /code
VOLUME /code
